import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../../assets/css/custom.css";

import Layout from "@/components/layouts";
import { UserProvider } from "../contexts/MyContext";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <UserProvider>
      <Suspense>
        <html lang="en" suppressHydrationWarning>
          <body>
            <Layout>{children}</Layout>
          </body>
        </html>
      </Suspense>
    </UserProvider>
  );
}
